import json
import os

languages = {
    "ar": {
        "commandCenter": "مركز القيادة",
        "knowledgeOS": "نظام تشغيل المعرفة",
        "manageAIModels": "إدارة نماذج الذكاء الاصطناعي",
        "loginFailed": "فشل تسجيل الدخول: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "غرفة الاستوديو",
        "listen": "استمع",
        "read": "اقرأ",
        "understand": "افهم",
        "remember": "تذكر",
        "quickNote": "ملاحظة سريعة",
        "listening": "يستمع...",
        "done": "تم",
        "wordList": "قائمة الكلمات",
        "wordListSubtitle": "قائمة المفردات",
        "timeline": "الجدول الزمني",
        "timelineSubtitle": "الجدول الزمني للتعلم",
        "wordListStats": "إحصائيات الكلمات",
        "wordListStatsSubtitle": "إحصائيات مفصلة",
        "webReader": "قارئ الويب",
        "webReaderSubtitle": "قراءة الويب + تمييز CEFR",
        "youtube": "يوتيوب",
        "youtubeSubtitle": "استكشاف القنوات الإنجليزية",
        "pdfReader": "قارئ PDF",
        "pdfReaderSubtitle": "فتح وقراءة ملفات PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "النطق الأصلي",
        "overview": "نظرة عامة",
        "overviewSubtitle": "تقدم التعلم",
        "wordMap": "خريطة الكلمات",
        "wordMapSubtitle": "معروف → صغير · غير معروف → كبير",
        "triangle": "مثلث",
        "triangleSubtitle": "خريطة + تقييم سريع",
        "vennDiagram": "مخطط فين",
        "vennDiagramSubtitle": "مناطق المهارات",
        "review": "مراجعة",
        "reviewSubtitle": "التكرار المتباعد SM-2",
        "shadowing": "التظليل",
        "shadowingSubtitle": "ممارسة التظليل",
        "dictation": "إملاء",
        "dictationSubtitle": "استمع واكتب",
        "audioLibrary": "مكتبة الصوت",
        "home": "الرئيسية",
        "tools": "أدوات",
        "nowPlaying": "يشتغل الآن",
        "typeVocabulary": "مفردات",
        "typePhrase": "عبارة",
        "typeSentence": "جملة",
        "typeParagraph": "فقرة",
        "typeDharma": "دارما",
        "typeGrammar": "قواعد",
        "diffEasy": "سهل",
        "diffMedium": "متوسط",
        "diffHard": "صعب",
        "vocabWord": "كلمة",
        "vocabPhrase": "عبارة",
        "vocabSentence": "جملة",
        "vocabParagraph": "فقرة"
    },
    "bn": {
        "commandCenter": "কমান্ড সেন্টার",
        "knowledgeOS": "নলেজ ওএস",
        "manageAIModels": "এআই মডেল পরিচালনা করুন",
        "loginFailed": "লগইন ব্যর্থ হয়েছে: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "স্টুডিও রুম",
        "listen": "শুনুন",
        "read": "পড়ুন",
        "understand": "বুঝুন",
        "remember": "মনে রাখুন",
        "quickNote": "দ্রুত নোট",
        "listening": "শুনছে...",
        "done": "সম্পন্ন",
        "wordList": "শব্দ তালিকা",
        "wordListSubtitle": "শব্দভান্ডার তালিকা",
        "timeline": "টাইমলাইন",
        "timelineSubtitle": "শেখার টাইমলাইন",
        "wordListStats": "শব্দ তালিকা পরিসংখ্যান",
        "wordListStatsSubtitle": "বিস্তারিত পরিসংখ্যান",
        "webReader": "ওয়েব রিডার",
        "webReaderSubtitle": "ওয়েব রিডিং + CEFR হাইলাইট",
        "youtube": "ইউটিউব",
        "youtubeSubtitle": "ইংরেজি চ্যানেল এক্সপ্লোর করুন",
        "pdfReader": "পিডিএফ রিডার",
        "pdfReaderSubtitle": "পিডিএফ ফাইল খুলুন এবং পড়ুন",
        "youglish": "YouGlish",
        "youglishSubtitle": "নেটিভ উচ্চারণ",
        "overview": "ওভারভিউ",
        "overviewSubtitle": "শেখার অগ্রগতি",
        "wordMap": "শব্দ মানচিত্র",
        "wordMapSubtitle": "জানা → ছোট · অজানা → বড়",
        "triangle": "ত্রিভুজ",
        "triangleSubtitle": "মানচিত্র + দ্রুত মূল্যায়ন",
        "vennDiagram": "ভেন ডায়াগ্রাম",
        "vennDiagramSubtitle": "দক্ষতা অঞ্চল",
        "review": "পর্যালোচনা",
        "reviewSubtitle": "SM-2 স্পেসড রিপিটেশন",
        "shadowing": "শ্যাডোইং",
        "shadowingSubtitle": "শ্যাডোইং অনুশীলন",
        "dictation": "শ্রুতলিপি",
        "dictationSubtitle": "শুনুন এবং টাইপ করুন",
        "audioLibrary": "অডিও লাইব্রেরি",
        "home": "হোম",
        "tools": "টুলস",
        "nowPlaying": "এখন বাজছে",
        "typeVocabulary": "শব্দভান্ডার",
        "typePhrase": "বাক্যাংশ",
        "typeSentence": "বাক্য",
        "typeParagraph": "অনুচ্ছেদ",
        "typeDharma": "ধর্ম",
        "typeGrammar": "ব্যাকরণ",
        "diffEasy": "সহজ",
        "diffMedium": "মাঝারি",
        "diffHard": "কঠিন",
        "vocabWord": "শব্দ",
        "vocabPhrase": "বাক্যাংশ",
        "vocabSentence": "বাক্য",
        "vocabParagraph": "অনুচ্ছেদ"
    },
    "bo": {
        "commandCenter": "བཀོད་འདོམས་ལྟེ་གནས།",
        "knowledgeOS": "ཤེས་བྱའི་མ་ལག",
        "manageAIModels": "AI དཔེ་དབྱིབས་དོ་དམ།",
        "loginFailed": "ནང་འཛུལ་ཕམ་ཉེས་བྱུང་བ།: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "སྒྲ་ཕབ་ཁང་།",
        "listen": "ཉན་པ།",
        "read": "ཀློག་པ།",
        "understand": "གོ་བ།",
        "remember": "ངེས་པ།",
        "quickNote": "མྱུར་བྲིས།",
        "listening": "ཉན་བཞིན་པ...",
        "done": "ལེགས་གྲུབ།",
        "wordList": "ཐ་སྙད་ཐོ་གཞུང་།",
        "wordListSubtitle": "ཐ་སྙད་ཐོ་གཞུང་།",
        "timeline": "དུས་ཚིགས།",
        "timelineSubtitle": "སློབ་སྦྱོང་གི་དུས་ཚིགས།",
        "wordListStats": "ཐ་སྙད་སྡོམ་རྩིས།",
        "wordListStatsSubtitle": "ཞིབ་ཕྲའི་སྡོམ་རྩིས།",
        "webReader": "དྲ་བ་ཀློག་ཆས།",
        "webReaderSubtitle": "དྲ་བ་ཀློག་པ + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "དབྱིན་ཡིག་གི་བརྙན་ལམ་འཚོལ་བ།",
        "pdfReader": "PDF ཀློག་ཆས།",
        "pdfReaderSubtitle": "PDF ཡིག་ཆ་ཁ་ཕྱེ་ནས་ཀློག་པ།",
        "youglish": "YouGlish",
        "youglishSubtitle": "ས་སྐྱེས་རྡོ་ཚུགས་ཀྱི་སྒྲ་གདངས།",
        "overview": "སྤྱི་ཡོངས།",
        "overviewSubtitle": "སློབ་སྦྱོང་གི་མྱུར་ཚད།",
        "wordMap": "ཐ་སྙད་ས་བཀྲ།",
        "wordMapSubtitle": "ཤེས་པ → ཆུང་བ · མ་ཤེས་པ → ཆེ་བ",
        "triangle": "ཟུར་གསུམ་མ།",
        "triangleSubtitle": "ས་བཀྲ + མྱུར་དུ་དཔྱད་འཇོག་བྱེད་པ།",
        "vennDiagram": "Venn རི་མོ།",
        "vennDiagramSubtitle": "རྩལ་ནུས་ཁུལ།",
        "review": "བསྐྱར་སྦྱོང་།",
        "reviewSubtitle": "SM-2 བར་སྟོང་ཅན་གྱི་བསྐྱར་ཟློས།",
        "shadowing": "གྲིབ་གཟུགས།",
        "shadowingSubtitle": "གྲིབ་གཟུགས་སྦྱོང་བརྡར།",
        "dictation": "ཡིག་རྒྱུགས་ལེན་པ།",
        "dictationSubtitle": "ཉན་ནས་ཡི་གེ་གཏགས་པ།",
        "audioLibrary": "སྒྲ་མཛོད།",
        "home": "གཙོ་ངོས།",
        "tools": "ལག་ཆ།",
        "nowPlaying": "ད་ལྟ་གཏོང་བཞིན་པ།",
        "typeVocabulary": "ཐ་སྙད།",
        "typePhrase": "ཚིག་ཐུང་།",
        "typeSentence": "ཚིག",
        "typeParagraph": "དུམ་བུ།",
        "typeDharma": "ཆོས་ལུགས།",
        "typeGrammar": "བརྡ་སྤྲོད།",
        "diffEasy": "སླ་བོ།",
        "diffMedium": "འབྲིང་བ།",
        "diffHard": "དཀའ་བོ།",
        "vocabWord": "མིང་ཚིག",
        "vocabPhrase": "ཚིག་ཐུང་།",
        "vocabSentence": "ཚིག",
        "vocabParagraph": "དུམ་བུ།"
    },
    "de": {
        "commandCenter": "KOMMANDOZENTRALE",
        "knowledgeOS": "Wissens-OS",
        "manageAIModels": "KI-Modelle verwalten",
        "loginFailed": "Anmeldung fehlgeschlagen: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "STUDIORAUM",
        "listen": "HÖREN",
        "read": "LESEN",
        "understand": "VERSTEHEN",
        "remember": "MERKEN",
        "quickNote": "Schnellnotiz",
        "listening": "Zuhören...",
        "done": "Fertig",
        "wordList": "Wortliste",
        "wordListSubtitle": "Vokabelliste",
        "timeline": "Zeitleiste",
        "timelineSubtitle": "Lernzeitleiste",
        "wordListStats": "Wortlisten-Statistiken",
        "wordListStatsSubtitle": "Detaillierte Statistiken",
        "webReader": "Web-Reader",
        "webReaderSubtitle": "Web-Lesen + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Englische Kanäle erkunden",
        "pdfReader": "PDF-Reader",
        "pdfReaderSubtitle": "PDF-Dateien öffnen & lesen",
        "youglish": "YouGlish",
        "youglishSubtitle": "Muttersprachliche Aussprache",
        "overview": "Übersicht",
        "overviewSubtitle": "Lernfortschritt",
        "wordMap": "Wortkarte",
        "wordMapSubtitle": "Bekannt → Klein · Unbekannt → Groß",
        "triangle": "Dreieck",
        "triangleSubtitle": "Karte + Schnelleinschätzung",
        "vennDiagram": "Venn-Diagramm",
        "vennDiagramSubtitle": "Fähigkeitszonen",
        "review": "Wiederholung",
        "reviewSubtitle": "SM-2 Spaced Repetition",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "Shadowing-Übung",
        "dictation": "Diktat",
        "dictationSubtitle": "Zuhören & Tippen",
        "audioLibrary": "Audio-Bibliothek",
        "home": "Start",
        "tools": "Werkzeuge",
        "nowPlaying": "Läuft jetzt",
        "typeVocabulary": "Vokabular",
        "typePhrase": "Phrase",
        "typeSentence": "Satz",
        "typeParagraph": "Absatz",
        "typeDharma": "Dharma",
        "typeGrammar": "Grammatik",
        "diffEasy": "Einfach",
        "diffMedium": "Mittel",
        "diffHard": "Schwer",
        "vocabWord": "Wort",
        "vocabPhrase": "Phrase",
        "vocabSentence": "Satz",
        "vocabParagraph": "Absatz"
    },
    "es": {
        "commandCenter": "CENTRO DE MANDO",
        "knowledgeOS": "Sistema Operativo de Conocimiento",
        "manageAIModels": "Gestionar modelos de IA",
        "loginFailed": "Error de inicio de sesión: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "SALA DE ESTUDIO",
        "listen": "ESCUCHAR",
        "read": "LEER",
        "understand": "ENTENDER",
        "remember": "RECORDAR",
        "quickNote": "Nota Rápida",
        "listening": "Escuchando...",
        "done": "Hecho",
        "wordList": "Lista de Palabras",
        "wordListSubtitle": "Lista de vocabulario",
        "timeline": "Línea de Tiempo",
        "timelineSubtitle": "Línea de tiempo de aprendizaje",
        "wordListStats": "Estadísticas de Palabras",
        "wordListStatsSubtitle": "Estadísticas detalladas",
        "webReader": "Lector Web",
        "webReaderSubtitle": "Lectura Web + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Explorar canales en inglés",
        "pdfReader": "Lector de PDF",
        "pdfReaderSubtitle": "Abrir y leer archivos PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "Pronunciación nativa",
        "overview": "Resumen",
        "overviewSubtitle": "Progreso de aprendizaje",
        "wordMap": "Mapa de Palabras",
        "wordMapSubtitle": "Conocido → Pequeño · Desconocido → Grande",
        "triangle": "Triángulo",
        "triangleSubtitle": "Mapa + Evaluación rápida",
        "vennDiagram": "Diagrama de Venn",
        "vennDiagramSubtitle": "Zonas de habilidades",
        "review": "Repasar",
        "reviewSubtitle": "Repetición espaciada SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "Práctica de Shadowing",
        "dictation": "Dictado",
        "dictationSubtitle": "Escuchar y escribir",
        "audioLibrary": "Biblioteca de Audio",
        "home": "Inicio",
        "tools": "Herramientas",
        "nowPlaying": "Reproduciendo",
        "typeVocabulary": "Vocabulario",
        "typePhrase": "Frase",
        "typeSentence": "Oración",
        "typeParagraph": "Párrafo",
        "typeDharma": "Dharma",
        "typeGrammar": "Gramática",
        "diffEasy": "Fácil",
        "diffMedium": "Medio",
        "diffHard": "Difícil",
        "vocabWord": "Palabra",
        "vocabPhrase": "Frase",
        "vocabSentence": "Oración",
        "vocabParagraph": "Párrafo"
    },
    "fr": {
        "commandCenter": "CENTRE DE COMMANDEMENT",
        "knowledgeOS": "OS de Connaissance",
        "manageAIModels": "Gérer les modèles d'IA",
        "loginFailed": "Échec de connexion : {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "SALLE DE STUDIO",
        "listen": "ÉCOUTER",
        "read": "LIRE",
        "understand": "COMPRENDRE",
        "remember": "RETENIR",
        "quickNote": "Note rapide",
        "listening": "Écoute...",
        "done": "Terminé",
        "wordList": "Liste de Mots",
        "wordListSubtitle": "Liste de vocabulaire",
        "timeline": "Chronologie",
        "timelineSubtitle": "Chronologie d'apprentissage",
        "wordListStats": "Statistiques des Mots",
        "wordListStatsSubtitle": "Statistiques détaillées",
        "webReader": "Lecteur Web",
        "webReaderSubtitle": "Lecture Web + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Explorer les chaînes anglaises",
        "pdfReader": "Lecteur PDF",
        "pdfReaderSubtitle": "Ouvrir et lire des fichiers PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "Prononciation native",
        "overview": "Aperçu",
        "overviewSubtitle": "Progrès d'apprentissage",
        "wordMap": "Carte des Mots",
        "wordMapSubtitle": "Connu → Petit · Inconnu → Grand",
        "triangle": "Triangle",
        "triangleSubtitle": "Carte + Évaluation rapide",
        "vennDiagram": "Diagramme de Venn",
        "vennDiagramSubtitle": "Zones de compétences",
        "review": "Réviser",
        "reviewSubtitle": "Répétition espacée SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "Pratique de Shadowing",
        "dictation": "Dictée",
        "dictationSubtitle": "Écouter et taper",
        "audioLibrary": "Bibliothèque Audio",
        "home": "Accueil",
        "tools": "Outils",
        "nowPlaying": "En cours",
        "typeVocabulary": "Vocabulaire",
        "typePhrase": "Expression",
        "typeSentence": "Phrase",
        "typeParagraph": "Paragraphe",
        "typeDharma": "Dharma",
        "typeGrammar": "Grammaire",
        "diffEasy": "Facile",
        "diffMedium": "Moyen",
        "diffHard": "Difficile",
        "vocabWord": "Mot",
        "vocabPhrase": "Expression",
        "vocabSentence": "Phrase",
        "vocabParagraph": "Paragraphe"
    },
    "id": {
        "commandCenter": "PUSAT KOMANDO",
        "knowledgeOS": "OS Pengetahuan",
        "manageAIModels": "Kelola Model AI",
        "loginFailed": "Login gagal: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "RUANG STUDIO",
        "listen": "DENGAR",
        "read": "BACA",
        "understand": "PAHAM",
        "remember": "INGAT",
        "quickNote": "Catatan Cepat",
        "listening": "Mendengarkan...",
        "done": "Selesai",
        "wordList": "Daftar Kata",
        "wordListSubtitle": "Daftar kosakata",
        "timeline": "Linimasa",
        "timelineSubtitle": "Linimasa pembelajaran",
        "wordListStats": "Statistik Daftar Kata",
        "wordListStatsSubtitle": "Statistik terperinci",
        "webReader": "Pembaca Web",
        "webReaderSubtitle": "Membaca Web + Sorotan CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Jelajahi Saluran Bahasa Inggris",
        "pdfReader": "Pembaca PDF",
        "pdfReaderSubtitle": "Buka & Baca File PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "Pelafalan asli",
        "overview": "Ikhtisar",
        "overviewSubtitle": "Kemajuan Pembelajaran",
        "wordMap": "Peta Kata",
        "wordMapSubtitle": "Diketahui → Kecil · Tidak Diketahui → Besar",
        "triangle": "Segitiga",
        "triangleSubtitle": "Peta + Penilaian Cepat",
        "vennDiagram": "Diagram Venn",
        "vennDiagramSubtitle": "Zona Keterampilan",
        "review": "Ulasan",
        "reviewSubtitle": "Pengulangan Berjarak SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "Latihan Shadowing",
        "dictation": "Dikte",
        "dictationSubtitle": "Dengar & Ketik",
        "audioLibrary": "Perpustakaan Audio",
        "home": "Beranda",
        "tools": "Alat",
        "nowPlaying": "Sedang Diputar",
        "typeVocabulary": "Kosakata",
        "typePhrase": "Frasa",
        "typeSentence": "Kalimat",
        "typeParagraph": "Paragraf",
        "typeDharma": "Dharma",
        "typeGrammar": "Tata Bahasa",
        "diffEasy": "Mudah",
        "diffMedium": "Sedang",
        "diffHard": "Sulit",
        "vocabWord": "Kata",
        "vocabPhrase": "Frasa",
        "vocabSentence": "Kalimat",
        "vocabParagraph": "Paragraf"
    },
    "it": {
        "commandCenter": "CENTRO DI COMANDO",
        "knowledgeOS": "OS della Conoscenza",
        "manageAIModels": "Gestisci modelli AI",
        "loginFailed": "Accesso fallito: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "SALA STUDIO",
        "listen": "ASCOLTA",
        "read": "LEGGI",
        "understand": "CAPIRE",
        "remember": "RICORDARE",
        "quickNote": "Nota rapida",
        "listening": "In ascolto...",
        "done": "Fatto",
        "wordList": "Lista di Parole",
        "wordListSubtitle": "Lista dei vocaboli",
        "timeline": "Cronologia",
        "timelineSubtitle": "Cronologia di apprendimento",
        "wordListStats": "Statistiche Lista Parole",
        "wordListStatsSubtitle": "Statistiche dettagliate",
        "webReader": "Lettore Web",
        "webReaderSubtitle": "Lettura Web + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Esplora i canali inglesi",
        "pdfReader": "Lettore PDF",
        "pdfReaderSubtitle": "Apri e leggi file PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "Pronuncia madrelingua",
        "overview": "Panoramica",
        "overviewSubtitle": "Progresso di apprendimento",
        "wordMap": "Mappa delle Parole",
        "wordMapSubtitle": "Conosciuto → Piccolo · Sconosciuto → Grande",
        "triangle": "Triangolo",
        "triangleSubtitle": "Mappa + Valutazione rapida",
        "vennDiagram": "Diagramma di Venn",
        "vennDiagramSubtitle": "Zone di competenza",
        "review": "Ripasso",
        "reviewSubtitle": "Ripetizione dilazionata SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "Pratica di Shadowing",
        "dictation": "Dettato",
        "dictationSubtitle": "Ascolta e scrivi",
        "audioLibrary": "Libreria Audio",
        "home": "Home",
        "tools": "Strumenti",
        "nowPlaying": "In riproduzione",
        "typeVocabulary": "Vocabolario",
        "typePhrase": "Frase (Espressione)",
        "typeSentence": "Frase (Orase)",
        "typeParagraph": "Paragrafo",
        "typeDharma": "Dharma",
        "typeGrammar": "Grammatica",
        "diffEasy": "Facile",
        "diffMedium": "Medio",
        "diffHard": "Difficile",
        "vocabWord": "Parola",
        "vocabPhrase": "Espressione",
        "vocabSentence": "Frase",
        "vocabParagraph": "Paragrafo"
    },
    "ja": {
        "commandCenter": "コマンドセンター",
        "knowledgeOS": "知識 OS",
        "manageAIModels": "AI モデルの管理",
        "loginFailed": "ログイン失敗: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "スタジオルーム",
        "listen": "聞く",
        "read": "読む",
        "understand": "理解する",
        "remember": "覚える",
        "quickNote": "クイックメモ",
        "listening": "聞いています...",
        "done": "完了",
        "wordList": "単語リスト",
        "wordListSubtitle": "語彙リスト",
        "timeline": "タイムライン",
        "timelineSubtitle": "学習タイムライン",
        "wordListStats": "単語統計",
        "wordListStatsSubtitle": "詳細な統計情報",
        "webReader": "Web リーダー",
        "webReaderSubtitle": "Web リーディング + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "英語チャンネルを探索",
        "pdfReader": "PDF リーダー",
        "pdfReaderSubtitle": "PDF ファイルを開いて読む",
        "youglish": "YouGlish",
        "youglishSubtitle": "ネイティブの発音",
        "overview": "概要",
        "overviewSubtitle": "学習の進捗",
        "wordMap": "単語マップ",
        "wordMapSubtitle": "知っている → 小 · 知らない → 大",
        "triangle": "トライアングル",
        "triangleSubtitle": "マップ + 迅速な評価",
        "vennDiagram": "ベン図",
        "vennDiagramSubtitle": "スキルゾーン",
        "review": "復習",
        "reviewSubtitle": "SM-2 間隔反復",
        "shadowing": "シャドーイング",
        "shadowingSubtitle": "シャドーイング練習",
        "dictation": "ディクテーション",
        "dictationSubtitle": "聞いて入力",
        "audioLibrary": "オーディオライブラリ",
        "home": "ホーム",
        "tools": "ツール",
        "nowPlaying": "再生中",
        "typeVocabulary": "語彙",
        "typePhrase": "フレーズ",
        "typeSentence": "文",
        "typeParagraph": "段落",
        "typeDharma": "Dharma",
        "typeGrammar": "文法",
        "diffEasy": "簡単",
        "diffMedium": "普通",
        "diffHard": "難しい",
        "vocabWord": "単語",
        "vocabPhrase": "フレーズ",
        "vocabSentence": "文",
        "vocabParagraph": "段落"
    },
    "km": {
        "commandCenter": "មជ្ឈមណ្ឌលបញ្ជា",
        "knowledgeOS": "ប្រព័ន្ធប្រតិបត្តិការចំណេះដឹង",
        "manageAIModels": "គ្រប់គ្រងម៉ូដែល AI",
        "loginFailed": "ការចូលបរាជ័យ: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "បន្ទប់ស្ទូឌីយោ",
        "listen": "ស្តាប់",
        "read": "អាន",
        "understand": "យល់",
        "remember": "ចងចាំ",
        "quickNote": "កំណត់ចំណាំរហ័ស",
        "listening": "កំពុងស្តាប់...",
        "done": "រួចរាល់",
        "wordList": "បញ្ជីពាក្យ",
        "wordListSubtitle": "បញ្ជីវាក្យសព្ទ",
        "timeline": "បន្ទាត់ពេលវេលា",
        "timelineSubtitle": "បន្ទាត់ពេលវេលាសិក្សា",
        "wordListStats": "ស្ថិតិបញ្ជីពាក្យ",
        "wordListStatsSubtitle": "ស្ថិតិលម្អិត",
        "webReader": "កម្មវិធីអានគេហទំព័រ",
        "webReaderSubtitle": "ការអានគេហទំព័រ + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "រុករកប៉ុស្តិ៍ភាសាអង់គ្លេស",
        "pdfReader": "កម្មវិធីអាន PDF",
        "pdfReaderSubtitle": "បើក និងអានឯកសារ PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "ការបញ្ចេញសំឡេងដើម",
        "overview": "ទិដ្ឋភាពទូទៅ",
        "overviewSubtitle": "វឌ្ឍនភាពសិក្សា",
        "wordMap": "ផែនទីពាក្យ",
        "wordMapSubtitle": "ដឹង → តូច · មិនដឹង → ធំ",
        "triangle": "ត្រីកោណ",
        "triangleSubtitle": "ផែនទី + ការវាយតម្លៃរហ័ស",
        "vennDiagram": "គំនូសបំព្រួញ Venn",
        "vennDiagramSubtitle": "តំបន់ជំនាញ",
        "review": "រំលឹកឡើងវិញ",
        "reviewSubtitle": "ការធ្វើឡើងវិញតាមចន្លោះ SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "ការអនុវត្ត Shadowing",
        "dictation": "សរសេរតាមអាន",
        "dictationSubtitle": "ស្តាប់និងវាយបញ្ចូល",
        "audioLibrary": "បណ្ណាល័យសំឡេង",
        "home": "ទំព័រដើម",
        "tools": "ឧបករណ៍",
        "nowPlaying": "កំពុងលេង",
        "typeVocabulary": "វាក្យសព្ទ",
        "typePhrase": "ឃ្លា",
        "typeSentence": "ប្រយោគ",
        "typeParagraph": "កថាខណ្ឌ",
        "typeDharma": "ធម៌",
        "typeGrammar": "វេយ្យាករណ៍",
        "diffEasy": "ងាយស្រួល",
        "diffMedium": "មធ្យម",
        "diffHard": "ពិបាក",
        "vocabWord": "ពាក្យ",
        "vocabPhrase": "ឃ្លា",
        "vocabSentence": "ប្រយោគ",
        "vocabParagraph": "កថាខណ្ឌ"
    },
    "ko": {
        "commandCenter": "커맨드 센터",
        "knowledgeOS": "지식 OS",
        "manageAIModels": "AI 모델 관리",
        "loginFailed": "로그인 실패: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "스튜디오 룸",
        "listen": "듣기",
        "read": "읽기",
        "understand": "이해하기",
        "remember": "기억하기",
        "quickNote": "빠른 메모",
        "listening": "듣는 중...",
        "done": "완료",
        "wordList": "단어장",
        "wordListSubtitle": "어휘 목록",
        "timeline": "타임라인",
        "timelineSubtitle": "학습 타임라인",
        "wordListStats": "단어 통계",
        "wordListStatsSubtitle": "자세한 통계",
        "webReader": "웹 리더",
        "webReaderSubtitle": "웹 읽기 + CEFR 하이라이트",
        "youtube": "YouTube",
        "youtubeSubtitle": "영어 채널 탐색",
        "pdfReader": "PDF 리더",
        "pdfReaderSubtitle": "PDF 파일 열기 및 읽기",
        "youglish": "YouGlish",
        "youglishSubtitle": "원어민 발음",
        "overview": "개요",
        "overviewSubtitle": "학습 진행 상황",
        "wordMap": "단어 맵",
        "wordMapSubtitle": "아는 단어 → 작게 · 모르는 단어 → 크게",
        "triangle": "트라이앵글",
        "triangleSubtitle": "맵 + 빠른 평가",
        "vennDiagram": "벤 다이어그램",
        "vennDiagramSubtitle": "스킬 영역",
        "review": "복습",
        "reviewSubtitle": "SM-2 간격 반복",
        "shadowing": "섀도잉",
        "shadowingSubtitle": "섀도잉 연습",
        "dictation": "받아쓰기",
        "dictationSubtitle": "듣고 타이핑",
        "audioLibrary": "오디오 라이브러리",
        "home": "홈",
        "tools": "도구",
        "nowPlaying": "재생 중",
        "typeVocabulary": "어휘",
        "typePhrase": "구",
        "typeSentence": "문장",
        "typeParagraph": "단락",
        "typeDharma": "Dharma",
        "typeGrammar": "문법",
        "diffEasy": "쉬움",
        "diffMedium": "보통",
        "diffHard": "어려움",
        "vocabWord": "단어",
        "vocabPhrase": "구",
        "vocabSentence": "문장",
        "vocabParagraph": "단락"
    },
    "lo": {
        "commandCenter": "ສູນຄວບຄຸມ",
        "knowledgeOS": "ລະບົບປະຕິບັດການຄວາມຮູ້",
        "manageAIModels": "ຈັດການໂມເດວ AI",
        "loginFailed": "ເຂົ້າສູ່ລະບົບລົ້ມເຫລວ: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "ຫ້ອງສະຕູດິໂອ",
        "listen": "ຟັງ",
        "read": "ອ່ານ",
        "understand": "ເຂົ້າໃຈ",
        "remember": "ຈື່",
        "quickNote": "ບັນທຶກດ່ວນ",
        "listening": "ກຳລັງຟັງ...",
        "done": "ສຳເລັດ",
        "wordList": "ລາຍການຄຳສັບ",
        "wordListSubtitle": "ລາຍການຄຳສັບ",
        "timeline": "ທາມລາຍ",
        "timelineSubtitle": "ທາມລາຍການຮຽນຮູ້",
        "wordListStats": "ສະຖິຕິຄຳສັບ",
        "wordListStatsSubtitle": "ສະຖິຕິລາຍລະອຽດ",
        "webReader": "ໂປຣແກຣມອ່ານເວັບ",
        "webReaderSubtitle": "ອ່ານເວັບ + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "ສຳຫຼວດຊ່ອງພາສາອັງກິດ",
        "pdfReader": "ໂປຣແກຣມອ່ານ PDF",
        "pdfReaderSubtitle": "ເປີດ ແລະ ອ່ານໄຟລ໌ PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "ການອອກສຽງພື້ນເມືອງ",
        "overview": "ພາບລວມ",
        "overviewSubtitle": "ຄວາມຄືບໜ້າການຮຽນ",
        "wordMap": "ແຜນທີ່ຄຳສັບ",
        "wordMapSubtitle": "ຮູ້ → ນ້ອຍ · ບໍ່ຮູ້ → ໃຫຍ່",
        "triangle": "ສາມຫຼ່ຽມ",
        "triangleSubtitle": "ແຜນທີ່ + ການປະເມີນດ່ວນ",
        "vennDiagram": "ແຜນວາດເວນ",
        "vennDiagramSubtitle": "ເຂດທັກສະ",
        "review": "ທົບທວນ",
        "reviewSubtitle": "ການເຮັດຊ້ຳແບບມີໄລຍະຫ່າງ SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "ການຝຶກ Shadowing",
        "dictation": "ຂຽນຕາມຄຳບອກ",
        "dictationSubtitle": "ຟັງ ແລະ ພິມ",
        "audioLibrary": "ຫ້ອງສະໝຸດສຽງ",
        "home": "ໜ້າຫຼັກ",
        "tools": "ເຄື່ອງມື",
        "nowPlaying": "ກຳລັງຫຼິ້ນ",
        "typeVocabulary": "ຄຳສັບ",
        "typePhrase": "ວະລີ",
        "typeSentence": "ປະໂຫຍກ",
        "typeParagraph": "ຫຍໍ້ໜ້າ",
        "typeDharma": "ທຳມະ",
        "typeGrammar": "ໄວຍາກອນ",
        "diffEasy": "ງ່າຍ",
        "diffMedium": "ປານກາງ",
        "diffHard": "ຍາກ",
        "vocabWord": "ຄຳສັບ",
        "vocabPhrase": "ວະລີ",
        "vocabSentence": "ປະໂຫຍກ",
        "vocabParagraph": "ຫຍໍ້ໜ້າ"
    },
    "mn": {
        "commandCenter": "КОМАНДЫН ТӨВ",
        "knowledgeOS": "Мэдлэгийн ҮС",
        "manageAIModels": "Хиймэл оюуны загвар удирдах",
        "loginFailed": "Нэвтрэхэд алдаа гарлаа: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "СТУДИЙН ӨРӨӨ",
        "listen": "СОНСОХ",
        "read": "УНШИХ",
        "understand": "ОЙЛГОХ",
        "remember": "САНАХ",
        "quickNote": "Шуурхай тэмдэглэл",
        "listening": "Сонсож байна...",
        "done": "Дууссан",
        "wordList": "Үгийн жагсаалт",
        "wordListSubtitle": "Үгсийн сангийн жагсаалт",
        "timeline": "Цагийн хуваарь",
        "timelineSubtitle": "Сургалтын цагийн хуваарь",
        "wordListStats": "Үгийн жагсаалтын статистик",
        "wordListStatsSubtitle": "Нарийвчилсан статистик",
        "webReader": "Вэб уншигч",
        "webReaderSubtitle": "Вэб унших + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Англи суваг судлах",
        "pdfReader": "PDF уншигч",
        "pdfReaderSubtitle": "PDF файл нээх болон унших",
        "youglish": "YouGlish",
        "youglishSubtitle": "Төрөлх дуудлага",
        "overview": "Тойм",
        "overviewSubtitle": "Сургалтын ахиц дэвшил",
        "wordMap": "Үгийн газрын зураг",
        "wordMapSubtitle": "Мэддэг → Жижиг · Мэдэхгүй → Том",
        "triangle": "Гурвалжин",
        "triangleSubtitle": "Газрын зураг + Шуурхай үнэлгээ",
        "vennDiagram": "Венн диаграмм",
        "vennDiagramSubtitle": "Ур чадварын бүс",
        "review": "Давтах",
        "reviewSubtitle": "SM-2 зайтай давталт",
        "shadowing": "Даган дуурайх (Shadowing)",
        "shadowingSubtitle": "Даган дуурайх дадлага",
        "dictation": "Цээж бичиг",
        "dictationSubtitle": "Сонсоод шивэх",
        "audioLibrary": "Аудио сан",
        "home": "Нүүр",
        "tools": "Хэрэгсэл",
        "nowPlaying": "Одоо тоглож байна",
        "typeVocabulary": "Үгсийн сан",
        "typePhrase": "Хэллэг",
        "typeSentence": "Өгүүлбэр",
        "typeParagraph": "Догол мөр",
        "typeDharma": "Ном",
        "typeGrammar": "Дүрэм",
        "diffEasy": "Амархан",
        "diffMedium": "Дунд",
        "diffHard": "Хэцүү",
        "vocabWord": "Үг",
        "vocabPhrase": "Хэллэг",
        "vocabSentence": "Өгүүлбэр",
        "vocabParagraph": "Догол мөр"
    },
    "mr": {
        "commandCenter": "कमांड सेंटर",
        "knowledgeOS": "नॉलेज ओएस",
        "manageAIModels": "AI मॉडेल्स व्यवस्थापित करा",
        "loginFailed": "लॉगिन अयशस्वी: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "स्टुडिओ रूम",
        "listen": "ऐका",
        "read": "वाचा",
        "understand": "समजून घ्या",
        "remember": "लक्षात ठेवा",
        "quickNote": "क्विक नोट",
        "listening": "ऐकत आहे...",
        "done": "झाले",
        "wordList": "शब्द सूची",
        "wordListSubtitle": "शब्दसंग्रह सूची",
        "timeline": "टाइमलाइन",
        "timelineSubtitle": "लर्निंग टाइमलाइन",
        "wordListStats": "शब्द सूची आकडेवारी",
        "wordListStatsSubtitle": "तपशीलवार आकडेवारी",
        "webReader": "वेब रीडर",
        "webReaderSubtitle": "वेब रीडिंग + CEFR हायलाइट",
        "youtube": "YouTube",
        "youtubeSubtitle": "इंग्रजी चॅनेल एक्सप्लोर करा",
        "pdfReader": "पीडीएफ रीडर",
        "pdfReaderSubtitle": "पीडीएफ फाइल्स उघडा आणि वाचा",
        "youglish": "YouGlish",
        "youglishSubtitle": "मूळ उच्चार",
        "overview": "आढावा",
        "overviewSubtitle": "शिकण्याची प्रगती",
        "wordMap": "शब्द नकाशा",
        "wordMapSubtitle": "ज्ञात → लहान · अज्ञात → मोठे",
        "triangle": "त्रिकोण",
        "triangleSubtitle": "नकाशा + द्रुत मूल्यांकन",
        "vennDiagram": "वेन डायग्राम",
        "vennDiagramSubtitle": "कौशल्य झोन",
        "review": "पुनरावलोकन",
        "reviewSubtitle": "SM-2 अंतरावरील पुनरावृत्ती",
        "shadowing": "शॅडोइंग",
        "shadowingSubtitle": "शॅडोइंग सराव",
        "dictation": "श्रुतलेखन",
        "dictationSubtitle": "ऐका आणि टाइप करा",
        "audioLibrary": "ऑडिओ लायब्ररी",
        "home": "होम",
        "tools": "साधने",
        "nowPlaying": "आता वाजत आहे",
        "typeVocabulary": "शब्दसंग्रह",
        "typePhrase": "वाक्यांश",
        "typeSentence": "वाक्य",
        "typeParagraph": "परिच्छेद",
        "typeDharma": "Dharma",
        "typeGrammar": "व्याकरण",
        "diffEasy": "सोपे",
        "diffMedium": "मध्यम",
        "diffHard": "कठीण",
        "vocabWord": "शब्द",
        "vocabPhrase": "वाक्यांश",
        "vocabSentence": "वाक्य",
        "vocabParagraph": "परिच्छेद"
    },
    "pt": {
        "commandCenter": "CENTRO DE COMANDO",
        "knowledgeOS": "SO de Conhecimento",
        "manageAIModels": "Gerenciar Modelos de IA",
        "loginFailed": "Falha no login: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "SALA DE ESTÚDIO",
        "listen": "OUVIR",
        "read": "LER",
        "understand": "ENTENDER",
        "remember": "LEMBRAR",
        "quickNote": "Nota Rápida",
        "listening": "Ouvindo...",
        "done": "Concluído",
        "wordList": "Lista de Palavras",
        "wordListSubtitle": "Lista de Vocabulário",
        "timeline": "Linha do Tempo",
        "timelineSubtitle": "Linha do tempo de aprendizado",
        "wordListStats": "Estatísticas de Palavras",
        "wordListStatsSubtitle": "Estatísticas detalhadas",
        "webReader": "Leitor da Web",
        "webReaderSubtitle": "Leitura na Web + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Explorar canais em inglês",
        "pdfReader": "Leitor de PDF",
        "pdfReaderSubtitle": "Abrir e ler arquivos PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "Pronúncia nativa",
        "overview": "Visão Geral",
        "overviewSubtitle": "Progresso de aprendizado",
        "wordMap": "Mapa de Palavras",
        "wordMapSubtitle": "Conhecido → Pequeno · Desconhecido → Grande",
        "triangle": "Triângulo",
        "triangleSubtitle": "Mapa + Avaliação rápida",
        "vennDiagram": "Diagrama de Venn",
        "vennDiagramSubtitle": "Zonas de habilidade",
        "review": "Revisar",
        "reviewSubtitle": "Repetição espaçada SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "Prática de Shadowing",
        "dictation": "Ditado",
        "dictationSubtitle": "Ouvir e digitar",
        "audioLibrary": "Biblioteca de Áudio",
        "home": "Início",
        "tools": "Ferramentas",
        "nowPlaying": "Reproduzindo agora",
        "typeVocabulary": "Vocabulário",
        "typePhrase": "Frase",
        "typeSentence": "Sentença",
        "typeParagraph": "Parágrafo",
        "typeDharma": "Dharma",
        "typeGrammar": "Gramática",
        "diffEasy": "Fácil",
        "diffMedium": "Médio",
        "diffHard": "Difícil",
        "vocabWord": "Palavra",
        "vocabPhrase": "Frase",
        "vocabSentence": "Sentença",
        "vocabParagraph": "Parágrafo"
    },
    "ru": {
        "commandCenter": "КОМАНДНЫЙ ЦЕНТР",
        "knowledgeOS": "ОС Знаний",
        "manageAIModels": "Управление моделями ИИ",
        "loginFailed": "Ошибка входа: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "СТУДИЯ",
        "listen": "СЛУШАТЬ",
        "read": "ЧИТАТЬ",
        "understand": "ПОНИМАТЬ",
        "remember": "ПОМНИТЬ",
        "quickNote": "Быстрая заметка",
        "listening": "Слушаю...",
        "done": "Готово",
        "wordList": "Список слов",
        "wordListSubtitle": "Словарный список",
        "timeline": "Хронология",
        "timelineSubtitle": "Хронология обучения",
        "wordListStats": "Статистика слов",
        "wordListStatsSubtitle": "Детальная статистика",
        "webReader": "Веб-ридер",
        "webReaderSubtitle": "Чтение в сети + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "Исследовать английские каналы",
        "pdfReader": "PDF Ридер",
        "pdfReaderSubtitle": "Открытие и чтение PDF файлов",
        "youglish": "YouGlish",
        "youglishSubtitle": "Произношение носителей",
        "overview": "Обзор",
        "overviewSubtitle": "Прогресс обучения",
        "wordMap": "Карта слов",
        "wordMapSubtitle": "Знаю → Мелкий · Не знаю → Крупный",
        "triangle": "Треугольник",
        "triangleSubtitle": "Карта + Быстрая оценка",
        "vennDiagram": "Диаграмма Венна",
        "vennDiagramSubtitle": "Зоны навыков",
        "review": "Повторение",
        "reviewSubtitle": "Интервальное повторение SM-2",
        "shadowing": "Теневой повтор",
        "shadowingSubtitle": "Практика теневого повтора",
        "dictation": "Диктант",
        "dictationSubtitle": "Слушай и печатай",
        "audioLibrary": "Аудиотека",
        "home": "Главная",
        "tools": "Инструменты",
        "nowPlaying": "Сейчас играет",
        "typeVocabulary": "Словарный запас",
        "typePhrase": "Фраза",
        "typeSentence": "Предложение",
        "typeParagraph": "Абзац",
        "typeDharma": "Дхарма",
        "typeGrammar": "Грамматика",
        "diffEasy": "Легко",
        "diffMedium": "Средне",
        "diffHard": "Сложно",
        "vocabWord": "Слово",
        "vocabPhrase": "Фраза",
        "vocabSentence": "Предложение",
        "vocabParagraph": "Абзац"
    },
    "ta": {
        "commandCenter": "கட்டளை மையம்",
        "knowledgeOS": "அறிவு OS",
        "manageAIModels": "AI மாடல்களை நிர்வகி",
        "loginFailed": "உள்நுழைவு தோல்வி: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "ஸ்டுடியோ அறை",
        "listen": "கேள்",
        "read": "படி",
        "understand": "புரிந்துகொள்",
        "remember": "நினைவில் கொள்",
        "quickNote": "விரைவான குறிப்பு",
        "listening": "கேட்கிறது...",
        "done": "முடிந்தது",
        "wordList": "சொல் பட்டியல்",
        "wordListSubtitle": "சொற்களஞ்சியப் பட்டியல்",
        "timeline": "காலக்கோடு",
        "timelineSubtitle": "கற்றல் காலக்கோடு",
        "wordListStats": "சொல் பட்டியல் புள்ளிவிவரம்",
        "wordListStatsSubtitle": "விரிவான புள்ளிவிவரங்கள்",
        "webReader": "வலை வாசகர்",
        "webReaderSubtitle": "வலை வாசிப்பு + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "ஆங்கில சேனல்களை ஆராயுங்கள்",
        "pdfReader": "PDF வாசகர்",
        "pdfReaderSubtitle": "PDF கோப்புகளைத் திறந்து படியுங்கள்",
        "youglish": "YouGlish",
        "youglishSubtitle": "பூர்வீக உச்சரிப்பு",
        "overview": "கண்ணோட்டம்",
        "overviewSubtitle": "கற்றல் முன்னேற்றம்",
        "wordMap": "சொல் வரைபடம்",
        "wordMapSubtitle": "தெரிந்தது → சிறியது · தெரியாதது → பெரியது",
        "triangle": "முக்கோணம்",
        "triangleSubtitle": "வரைபடம் + விரைவான மதிப்பீடு",
        "vennDiagram": "வென் வரைபடம்",
        "vennDiagramSubtitle": "திறன் மண்டலங்கள்",
        "review": "விமர்சனம்",
        "reviewSubtitle": "SM-2 இடைவெளித் திருப்பம்",
        "shadowing": "நிழலாடல்",
        "shadowingSubtitle": "நிழலாடல் பயிற்சி",
        "dictation": "சொல்வது எழுதுதல்",
        "dictationSubtitle": "கேட்டு தட்டச்சு செய்க",
        "audioLibrary": "ஆடியோ நூலகம்",
        "home": "முகப்பு",
        "tools": "கருவிகள்",
        "nowPlaying": "இப்போது ஒலிக்கிறது",
        "typeVocabulary": "சொற்களஞ்சியம்",
        "typePhrase": "சொற்றொடர்",
        "typeSentence": "வாக்கியம்",
        "typeParagraph": "பத்தி",
        "typeDharma": "Dharma",
        "typeGrammar": "இலக்கணம்",
        "diffEasy": "எளிது",
        "diffMedium": "நடுத்தரம்",
        "diffHard": "கடினம்",
        "vocabWord": "சொல்",
        "vocabPhrase": "சொற்றொடர்",
        "vocabSentence": "வாக்கியம்",
        "vocabParagraph": "பத்தி"
    },
    "te": {
        "commandCenter": "కమాండ్ సెంటర్",
        "knowledgeOS": "నాలెడ్జ్ OS",
        "manageAIModels": "AI మోడళ్లను నిర్వహించండి",
        "loginFailed": "లాగిన్ విఫలమైంది: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "స్టూడియో గది",
        "listen": "విను",
        "read": "చదువు",
        "understand": "అర్థం చేసుకో",
        "remember": "గుర్తుంచుకో",
        "quickNote": "త్వరిత గమనిక",
        "listening": "వింటోంది...",
        "done": "పూర్తయింది",
        "wordList": "పదాల జాబితా",
        "wordListSubtitle": "పదజాలం జాబితా",
        "timeline": "కాలక్రమం",
        "timelineSubtitle": "అభ్యాస కాలక్రమం",
        "wordListStats": "పదాల గణాంకాలు",
        "wordListStatsSubtitle": "వివరణాత్మక గణాంకాలు",
        "webReader": "వెబ్ రీడర్",
        "webReaderSubtitle": "వెబ్ పఠనం + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "ఆంగ్ల ఛానెల్‌లను అన్వేషించండి",
        "pdfReader": "PDF రీడర్",
        "pdfReaderSubtitle": "PDF ఫైల్‌లను తెరవండి & చదవండి",
        "youglish": "YouGlish",
        "youglishSubtitle": "స్థానిక ఉచ్చారణ",
        "overview": "అవలోకనం",
        "overviewSubtitle": "అభ్యాస పురోగతి",
        "wordMap": "పదాల మ్యాప్",
        "wordMapSubtitle": "తెలిసినవి → చిన్నవి · తెలియనివి → పెద్దవి",
        "triangle": "త్రికోణం",
        "triangleSubtitle": "మ్యాప్ + త్వరిత అంచనా",
        "vennDiagram": "వెన్ రేఖాచిత్రం",
        "vennDiagramSubtitle": "నైపుణ్య మండలాలు",
        "review": "సమీక్ష",
        "reviewSubtitle": "SM-2 ఖాళీతో పునరావృతం",
        "shadowing": "షాడోయింగ్",
        "shadowingSubtitle": "షాడోయింగ్ ప్రాక్టీస్",
        "dictation": "డిక్టేషన్",
        "dictationSubtitle": "విని టైప్ చేయండి",
        "audioLibrary": "ఆడియో లైబ్రరీ",
        "home": "హోమ్",
        "tools": "సాధనాలు",
        "nowPlaying": "ఇప్పుడు ప్లే అవుతోంది",
        "typeVocabulary": "పదజాలం",
        "typePhrase": "పదబంధం",
        "typeSentence": "వాక్యం",
        "typeParagraph": "పేరా",
        "typeDharma": "Dharma",
        "typeGrammar": "వ్యాకరణం",
        "diffEasy": "సులభం",
        "diffMedium": "మధ్యమం",
        "diffHard": "కష్టం",
        "vocabWord": "పదం",
        "vocabPhrase": "పదబంధం",
        "vocabSentence": "వాక్యం",
        "vocabParagraph": "పేరా"
    },
    "th": {
        "commandCenter": "ศูนย์ควบคุม",
        "knowledgeOS": "ระบบปฏิบัติการความรู้",
        "manageAIModels": "จัดการโมเดล AI",
        "loginFailed": "เข้าสู่ระบบล้มเหลว: {error}",
        "@loginFailed": {"placeholders": {"error": {"type": "String"}}},
        "studioRoom": "ห้องสตูดิโอ",
        "listen": "ฟัง",
        "read": "อ่าน",
        "understand": "เข้าใจ",
        "remember": "จดจำ",
        "quickNote": "จดบันทึกด่วน",
        "listening": "กำลังฟัง...",
        "done": "เสร็จสิ้น",
        "wordList": "รายการคำศัพท์",
        "wordListSubtitle": "รายการคำศัพท์",
        "timeline": "ไทม์ไลน์",
        "timelineSubtitle": "ไทม์ไลน์การเรียนรู้",
        "wordListStats": "สถิติคำศัพท์",
        "wordListStatsSubtitle": "สถิติโดยละเอียด",
        "webReader": "โปรแกรมอ่านเว็บ",
        "webReaderSubtitle": "อ่านเว็บ + CEFR",
        "youtube": "YouTube",
        "youtubeSubtitle": "สำรวจช่องภาษาอังกฤษ",
        "pdfReader": "โปรแกรมอ่าน PDF",
        "pdfReaderSubtitle": "เปิดและอ่านไฟล์ PDF",
        "youglish": "YouGlish",
        "youglishSubtitle": "การออกเสียงแบบเจ้าของภาษา",
        "overview": "ภาพรวม",
        "overviewSubtitle": "ความคืบหน้าการเรียนรู้",
        "wordMap": "แผนที่คำศัพท์",
        "wordMapSubtitle": "รู้ → เล็ก · ไม่รู้ → ใหญ่",
        "triangle": "สามเหลี่ยม",
        "triangleSubtitle": "แผนที่ + ประเมินด่วน",
        "vennDiagram": "แผนภาพเวนน์",
        "vennDiagramSubtitle": "โซนทักษะ",
        "review": "ทบทวน",
        "reviewSubtitle": "การทำซ้ำแบบเว้นระยะ SM-2",
        "shadowing": "Shadowing",
        "shadowingSubtitle": "ฝึก Shadowing",
        "dictation": "เขียนตามคำบอก",
        "dictationSubtitle": "ฟังและพิมพ์",
        "audioLibrary": "ห้องสมุดเสียง",
        "home": "หน้าแรก",
        "tools": "เครื่องมือ",
        "nowPlaying": "กำลังเล่น",
        "typeVocabulary": "คำศัพท์",
        "typePhrase": "วลี",
        "typeSentence": "ประโยค",
        "typeParagraph": "ย่อหน้า",
        "typeDharma": "ธรรมะ",
        "typeGrammar": "ไวยากรณ์",
        "diffEasy": "ง่าย",
        "diffMedium": "ปานกลาง",
        "diffHard": "ยาก",
        "vocabWord": "คำ",
        "vocabPhrase": "วลี",
        "vocabSentence": "ประโยค",
        "vocabParagraph": "ย่อหน้า"
    }
}

for lang, data in languages.items():
    data["@@locale"] = lang
    with open(f"lib/l10n/app_{lang}.arb", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Created arb files successfully!")
