name: vipsound
description: Read + Remember + Learn + Music Player with UltraTimeStretch Engine - Speed 0.05x to 10.0x

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Audio Playback
  just_audio_platform_interface: ^4.0.0
  just_audio: ^0.10.5
  just_audio_windows: ^0.2.1   # ← THÊM DÒNG NÀY!
  audio_session: ^0.2.2

  # FFI for Native C++ Engine
  ffi: ^2.1.3

  # File & Storage
  file_picker: ^11.0.2
  path_provider: ^2.1.4
  permission_handler: ^12.0.1

  # Utilities
  rxdart: ^0.28.0  # Stream utilities
  equatable: ^2.0.5

  cupertino_icons: ^1.0.8

  # NEW
  hive: ^2.2.3                    # Local database
  hive_flutter: ^1.1.0            # Hive cho Flutter
  audio_service: ^0.18.12         # Background playback

  uuid: ^4.2.1                    # Generate unique IDs
  share_plus: ^12.0.2              # Share segments
  shared_preferences: ^2.3.5  # THÊM DÒNG NÀY
  flutter_tts: ^4.2.0  # THÊM DÒNG NÀY
  just_waveform: ^0.0.7  # Đọc waveform từ audio file
  record: ^6.1.2 # ghi âm
  record_windows: ^1.0.1 # ★ BẮT BUỘC cho Windows
  oauth2: ^2.0.2
  url_launcher: ^6.2.5               # cho word_actions_sheet tra từ online

  http: ^1.2.2
  connectivity_plus: ^7.1.0    # Check network
  crypto: ^3.0.6                 # MD5 hash cho cache key
# Firebase core (bắt buộc)
  firebase_core: ^4.6.0 #change from 3.8.1
  
  # Firebase Auth (đăng nhập anonymous)
  firebase_auth: ^6.3.0
  
  # Cloud Firestore (database)
  cloud_firestore: ^6.2.0 #change from 5.5.0
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0

  # Youglish Android & iOS
  webview_flutter: ^4.9.0
  # Youglish Win
  webview_win_floating: ^3.0.0
  webview_windows: ^0.4.0   # Chỉ cho Windows
  # Youtube
  youtube_explode_dart: ^3.0.5
  pdfrx: ^2.2.24          # PDF render + text extraction (Android/iOS/Windows)
  graphview: ^1.2.0  
dependency_overrides:
  just_audio_platform_interface: 4.6.0  # KHÔNG dùng ^
  just_audio_web: 0.4.16                # KHÔNG dùng ^
  audio_session: 0.2.2                  # KHÔNG dùng ^

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1          # Generate Hive adapters
  build_runner: ^2.4.7            # Code generation
  flutter_launcher_icons: ^0.14.4
ffigen: ^9.1.3
flutter:
  uses-material-design: true
  assets:
    - assets/dictionary/    