# Generated code do not commit.
file(TO_CMAKE_PATH "/home/pabahassara/development/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/media/pabahassara/MEDIA1/PROJECTS/in4up" PROJECT_DIR)

set(FLUTTER_VERSION "1.4.1+3" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 4 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 1 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 3 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/pabahassara/development/flutter"
  "PROJECT_DIR=/media/pabahassara/MEDIA1/PROJECTS/in4up"
  "DART_DEFINES=RkxBVk9SPXN0YWJsZQ==,RkxVVFRFUl9BUFBfRkxBVk9SPXN0YWJsZQ==,RkxVVFRFUl9WRVJTSU9OPTMuNDEuOQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049MDBiMGM5MWYwNg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NDJkM2Q3NWE1Ng==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMS41"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=/media/pabahassara/MEDIA1/PROJECTS/in4up/.dart_tool/package_config.json"
  "FLAVOR=stable"
  "FLUTTER_TARGET=/media/pabahassara/MEDIA1/PROJECTS/in4up/lib/main.dart"
)
