org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=true
org.gradle.parallel=true

# Increase timeout
systemProp.http.connectionTimeout=180000
systemProp.http.socketTimeout=180000
systemProp.https.connectionTimeout=180000
systemProp.https.socketTimeout=180000