// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-xDY8nduuCp8-G_S1CPfyoyYdgWvCJCk',
    appId: '1:342774597309:web:777b459680ec02461319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    authDomain: 'vipsound-df903.firebaseapp.com',
    databaseURL: 'https://vipsound-df903-default-rtdb.firebaseio.com',
    storageBucket: 'vipsound-df903.firebasestorage.app',
    measurementId: 'G-N72C4S87J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsYaEwRBlZ3RW51DoElscbKx6X2JKP2dw',
    appId: '1:342774597309:android:e0a919b0fb77dd391319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    databaseURL: 'https://vipsound-df903-default-rtdb.firebaseio.com',
    storageBucket: 'vipsound-df903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNh1jlG74XV_VplhSSqL--jFYvVOrRig',
    appId: '1:342774597309:ios:f1643ab0df1208351319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    databaseURL: 'https://vipsound-df903-default-rtdb.firebaseio.com',
    storageBucket: 'vipsound-df903.firebasestorage.app',
    androidClientId: '342774597309-276p37a3jequc9hfp3vsrfn1b6jels0b.apps.googleusercontent.com',
    iosClientId: '342774597309-gk1uua5n5ldohtt4nroc8irie05bed4m.apps.googleusercontent.com',
    iosBundleId: 'com.in4up',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-xDY8nduuCp8-G_S1CPfyoyYdgWvCJCk',
    appId: '1:342774597309:web:777b459680ec02461319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    authDomain: 'vipsound-df903.firebaseapp.com',
    databaseURL: 'https://vipsound-df903-default-rtdb.firebaseio.com',
    storageBucket: 'vipsound-df903.firebasestorage.app',
    measurementId: 'G-N72C4S87J8',
  );
}
