// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-xDY8nduuCp8-G_S1CPfyoyYdgWvCJCk',
    appId: '1:342774597309:web:e57413d5393133891319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    authDomain: 'vipsound-df903.firebaseapp.com',
    storageBucket: 'vipsound-df903.firebasestorage.app',
    measurementId: 'G-2LS790VYV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsYaEwRBlZ3RW51DoElscbKx6X2JKP2dw',
    appId: '1:342774597309:android:1a2e3217ee3dc8ee1319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    storageBucket: 'vipsound-df903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNh1jlG74XV_VplhSSqL--jFYvVOrRig',
    appId: '1:342774597309:ios:73f47433d19cbae51319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    storageBucket: 'vipsound-df903.firebasestorage.app',
    iosBundleId: 'com.vipsound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-xDY8nduuCp8-G_S1CPfyoyYdgWvCJCk',
    appId: '1:342774597309:web:e2f9374feb0906c31319d4',
    messagingSenderId: '342774597309',
    projectId: 'vipsound-df903',
    authDomain: 'vipsound-df903.firebaseapp.com',
    storageBucket: 'vipsound-df903.firebasestorage.app',
    measurementId: 'G-Z5PYM6SE4G',
  );
}
