# tool/wp0_arb_inject_data.py — dữ liệu dịch cho WP0 (API-001) màn Server & API.
# 37 key mới. T2 (ADR-0002): dịch đủ vi/en/hi/zh/zh_TW/si trong cùng PR.
# 20 locale T3 khác dùng giá trị en (canonical fallback — đúng rule #5).

TRANSLATIONS = {
    "aiProvidersTitle": {
        "en": "AI Servers & API",
        "vi": "Server & API cho AI",
        "hi": "AI सर्वर और API",
        "zh": "AI 服务器与 API",
        "zh_TW": "AI 伺服器與 API",
        "si": "AI සේවාදායක සහ API",
    },
    "aiProvidersSubtitle": {
        "en": "Use cloud or home-server models. Offline remains the default.",
        "vi": "Dùng model từ cloud hoặc server trong nhà. Offline vẫn là mặc định.",
        "hi": "क्लाउड या घरेलू सर्वर मॉडल का उपयोग करें। ऑफ़लाइन डिफ़ॉल्ट बना रहेगा।",
        "zh": "使用云端或家庭服务器模型。默认仍为离线。",
        "zh_TW": "使用雲端或家庭伺服器模型。預設仍為離線。",
        "si": "වලාකුලෝස් හෝ ගෙදර සේවාදායකයේ ආකෘති භාවිත කරන්න. ඕෆ්ලයින් පෙරනිමිය ලෙසම පවතී.",
    },
    "aiProvidersEntryTitle": {
        "en": "Server & API (cloud / LAN)",
        "vi": "Server & API (mây / LAN)",
        "hi": "सर्वर और API (क्लाउड / LAN)",
        "zh": "服务器与 API（云端 / 局域网）",
        "zh_TW": "伺服器與 API（雲端 / 區域網路）",
        "si": "සේවාදායක සහ API (වලාකුල / LAN)",
    },
    "aiProvidersEntrySubtitle": {
        "en": "Add online models — frees RAM, offline stays as fallback",
        "vi": "Thêm model online — giải phóng RAM, offline vẫn dự phòng",
        "hi": "ऑनलाइन मॉडल जोड़ें — RAM खाली होगी, ऑफ़लाइन बैकअप बना रहेगा",
        "zh": "添加在线模型 — 释放内存，离线仍作后备",
        "zh_TW": "新增線上模型 — 釋放記憶體，離線仍作後備",
        "si": "සබඳි ආකෘති එක් කරන්න — RAM නිදහස් වේ, ඕෆ්ලයින් අතිරික්තය වේ",
    },
    "aiProvidersEmpty": {
        "en": "No provider configured. The app works fully offline, as before.",
        "vi": "Chưa cấu hình nhà cung cấp nào. App vẫn hoạt động offline đầy đủ như trước.",
        "hi": "कोई प्रोवाइडर सेट नहीं है। ऐप पहले की तरह पूरी तरह ऑफ़लाइन चलता है।",
        "zh": "尚未配置任何提供商。应用仍如往常完全离线运行。",
        "zh_TW": "尚未設定任何供應商。應用程式仍如往常完全離線運作。",
        "si": "කිසිදු සැපයුම්කරුවෙකු වින්‍යාසගත කර නැත. යෙදුම දැනටමත් සම්පූර්ණයෙන් ඕෆ්ලයින් ක්‍රියා කරයි.",
    },
    "aiProviderAdd": {
        "en": "Add provider",
        "vi": "Thêm nhà cung cấp",
        "hi": "प्रोवाइडर जोड़ें",
        "zh": "添加提供商",
        "zh_TW": "新增供應商",
        "si": "සැපයුම්කරු එක් කරන්න",
    },
    "aiProviderEdit": {
        "en": "Edit provider",
        "vi": "Sửa nhà cung cấp",
        "hi": "प्रोवाइडर संपादित करें",
        "zh": "编辑提供商",
        "zh_TW": "編輯供應商",
        "si": "සැපයුම්කරු සංස්කරණය කරන්න",
    },
    "aiProviderLabel": {
        "en": "Display name",
        "vi": "Tên hiển thị",
        "hi": "प्रदर्शित नाम",
        "zh": "显示名称",
        "zh_TW": "顯示名稱",
        "si": "පෙන්වන නම",
    },
    "aiProviderBaseUrl": {
        "en": "Server URL (baseUrl)",
        "vi": "Địa chỉ server (baseUrl)",
        "hi": "सर्वर URL (baseUrl)",
        "zh": "服务器地址 (baseUrl)",
        "zh_TW": "伺服器位址 (baseUrl)",
        "si": "සේවාදායක URL (baseUrl)",
    },
    "aiProviderApiKey": {
        "en": "API key",
        "vi": "API key",
        "hi": "API कुंजी",
        "zh": "API 密钥",
        "zh_TW": "API 金鑰",
        "si": "API යතුර",
    },
    "aiProviderApiKeyHint": {
        "en": "Leave empty for a home server",
        "vi": "Server nhà có thể bỏ trống",
        "hi": "घरेलू सर्वर के लिए खाली छोड़ें",
        "zh": "家庭服务器可留空",
        "zh_TW": "家庭伺服器可留空",
        "si": "ගෙදර සේවාදායකය සඳහා හිස්ව තබන්න",
    },
    "aiProviderPreset": {
        "en": "Preset",
        "vi": "Mẫu sẵn",
        "hi": "प्रीसेट",
        "zh": "预设",
        "zh_TW": "預設",
        "si": "කලින් සකසන ලද",
    },
    "aiProviderPresetCustom": {
        "en": "Custom…",
        "vi": "Tự nhập…",
        "hi": "कस्टम…",
        "zh": "自定义…",
        "zh_TW": "自訂…",
        "si": "අභිරුචි…",
    },
    "aiProviderTestConnection": {
        "en": "Test connection",
        "vi": "Kiểm tra kết nối",
        "hi": "कनेक्शन जाँचें",
        "zh": "测试连接",
        "zh_TW": "測試連線",
        "si": "සම්බන්ධය පරීක්ෂා කරන්න",
    },
    "aiProviderConnectionOk": {
        "en": "Connected",
        "vi": "Đã kết nối",
        "hi": "जुड़ा हुआ",
        "zh": "已连接",
        "zh_TW": "已連線",
        "si": "සම්බන්ධ වී ඇත",
    },
    "aiProviderConnectionFail": {
        "en": "Connection failed",
        "vi": "Kết nối thất bại",
        "hi": "कनेक्शन विफल",
        "zh": "连接失败",
        "zh_TW": "連線失敗",
        "si": "සම්බන්ධතාව අසාර්ථක විය",
    },
    "aiProviderLoadModels": {
        "en": "Load models",
        "vi": "Tải danh sách model",
        "hi": "मॉडल लोड करें",
        "zh": "加载模型列表",
        "zh_TW": "載入模型清單",
        "si": "ආකෘති පූරණය කරන්න",
    },
    "aiProviderModelsLabel": {
        "en": "models",
        "vi": "model",
        "hi": "मॉडल",
        "zh": "个模型",
        "zh_TW": "個模型",
        "si": "ආකෘති",
    },
    "aiProviderChatModel": {
        "en": "Chat / analysis model",
        "vi": "Model chat / phân tích",
        "hi": "चैट / विश्लेषण मॉडल",
        "zh": "聊天 / 分析模型",
        "zh_TW": "聊天 / 分析模型",
        "si": "කතාබහ / විශ්ලේෂණ ආකෘතිය",
    },
    "aiProviderSttModel": {
        "en": "Speech-to-text model",
        "vi": "Model bóc băng (STT)",
        "hi": "स्पीच-टू-टेक्स्ट मॉडल",
        "zh": "语音转文字模型",
        "zh_TW": "語音轉文字模型",
        "si": "කථන-සිට-පෙළ ආකෘතිය",
    },
    "aiProviderTtsModel": {
        "en": "Text-to-speech model",
        "vi": "Model đọc chữ (TTS)",
        "hi": "टेक्स्ट-टू-स्पीच मॉडल",
        "zh": "文字转语音模型",
        "zh_TW": "文字轉語音模型",
        "si": "පෙළ-සිට-කථන ආකෘතිය",
    },
    "aiProviderNoModels": {
        "en": "Load the model list first",
        "vi": "Hãy tải danh sách model trước",
        "hi": "पहले मॉडल सूची लोड करें",
        "zh": "请先加载模型列表",
        "zh_TW": "請先載入模型清單",
        "si": "පළමුව ආකෘති ලැයිස්තුව පූරණය කරන්න",
    },
    "aiProviderNone": {
        "en": "None",
        "vi": "Không dùng",
        "hi": "कोई नहीं",
        "zh": "不使用",
        "zh_TW": "不使用",
        "si": "නැත",
    },
    "aiProviderEnabled": {
        "en": "Enabled",
        "vi": "Đang bật",
        "hi": "सक्रिय",
        "zh": "已启用",
        "zh_TW": "已啟用",
        "si": "සක්‍රීයයි",
    },
    "aiProviderDelete": {
        "en": "Remove",
        "vi": "Xoá",
        "hi": "हटाएँ",
        "zh": "移除",
        "zh_TW": "移除",
        "si": "ඉවත් කරන්න",
    },
    "aiProviderDeleteConfirm": {
        "en": "Remove this provider and its settings?",
        "vi": "Xoá nhà cung cấp này cùng toàn bộ cấu hình?",
        "hi": "यह प्रोवाइडर और उसकी सेटिंग्स हटाएँ?",
        "zh": "移除此提供商及其设置？",
        "zh_TW": "移除此供應商及其設定？",
        "si": "මෙම සැපයුම්කරුවා සහ ඔහුගේ සැකසුම් ඉවත් කරන්නද?",
    },
    "aiRoutingTitle": {
        "en": "When to use online models",
        "vi": "Khi nào dùng model online",
        "hi": "ऑनलाइन मॉडल कब उपयोग करें",
        "zh": "何时使用在线模型",
        "zh_TW": "何時使用線上模型",
        "si": "සබඳි ආකෘති කවදා භාවිත කරන්නද",
    },
    "aiRoutingChat": {
        "en": "AI chat & analysis",
        "vi": "Chat & phân tích AI",
        "hi": "AI चैट और विश्लेषण",
        "zh": "AI 聊天与分析",
        "zh_TW": "AI 聊天與分析",
        "si": "AI කතාබහ සහ විශ්ලේෂණය",
    },
    "aiRoutingStt": {
        "en": "Transcribe audio files",
        "vi": "Bóc băng file audio",
        "hi": "ऑडियो फ़ाइल ट्रांसक्रिप्ट",
        "zh": "转录音频文件",
        "zh_TW": "轉錄音訊檔案",
        "si": "ශ්‍රව්‍ය ගොනු පිටපත් කරන්න",
    },
    "aiRoutingTranslation": {
        "en": "Translation",
        "vi": "Dịch thuật",
        "hi": "अनुवाद",
        "zh": "翻译",
        "zh_TW": "翻譯",
        "si": "පරිවර්තනය",
    },
    "aiRoutingTts": {
        "en": "Text-to-speech",
        "vi": "Đọc chữ (TTS)",
        "hi": "टेक्स्ट-टू-स्पीच",
        "zh": "文字转语音",
        "zh_TW": "文字轉語音",
        "si": "පෙළ-සිට-කථනය",
    },
    "aiRouteOfflineFirst": {
        "en": "Offline first",
        "vi": "Ưu tiên offline",
        "hi": "पहले ऑफ़लाइन",
        "zh": "优先离线",
        "zh_TW": "優先離線",
        "si": "පළමුව ඕෆ්ලයින්",
    },
    "aiRouteOnlineFirst": {
        "en": "Online first",
        "vi": "Ưu tiên online",
        "hi": "पहले ऑनलाइन",
        "zh": "优先在线",
        "zh_TW": "優先線上",
        "si": "පළමුව සබඳි",
    },
    "aiRouteOfflineOnly": {
        "en": "Offline only",
        "vi": "Chỉ offline",
        "hi": "केवल ऑफ़लाइन",
        "zh": "仅离线",
        "zh_TW": "僅離線",
        "si": "ඕෆ්ලයින් පමණි",
    },
    "aiRoutingProvider": {
        "en": "Provider",
        "vi": "Nhà cung cấp",
        "hi": "प्रोवाइडर",
        "zh": "提供商",
        "zh_TW": "供應商",
        "si": "සැපයුම්කරු",
    },
    "aiProviderSave": {
        "en": "Save",
        "vi": "Lưu",
        "hi": "सहेजें",
        "zh": "保存",
        "zh_TW": "儲存",
        "si": "සුරකින්න",
    },
    "aiProviderCancel": {
        "en": "Cancel",
        "vi": "Huỷ",
        "hi": "रद्द करें",
        "zh": "取消",
        "zh_TW": "取消",
        "si": "අවලංගු කරන්න",
    },
    "aiProvidersPrivacy": {
        "en": "Audio and text are sent only to the provider you choose. "
             "A home server (LAN) keeps data inside your network.",
        "vi": "Audio và text chỉ được gửi tới nhà cung cấp bạn chọn. "
              "Server nhà (LAN) giữ dữ liệu trong mạng của bạn.",
        "hi": "ऑडियो और टेक्स्ट केवल आपके चुने प्रोवाइडर को भेजे जाते हैं। "
              "घरेलू सर्वर (LAN) डेटा आपके नेटवर्क में ही रखता है।",
        "zh": "音频和文本仅发送到您选择的提供商。家庭服务器（局域网）让数据留在您的网络内。",
        "zh_TW": "音訊和文字僅傳送到您選擇的供應商。家庭伺服器（區域網路）讓資料留在您的網路內。",
        "si": "ශ්‍රව්‍ය සහ පෙළ ඔබ තෝරාගත් සැපයුම්කරුට පමණක් යවයි. "
              "ගෙදර සේවාදායකය (LAN) දත්ත ඔබගේ ජාලය තුළ රඳවා ගනී.",
    },
}
